# Generated by Django 4.0.6 on 2022-07-08 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canvas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('canvas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='mindmap.canvas')),
                ('links', models.ManyToManyField(blank=True, null=True, to='mindmap.node')),
            ],
        ),
    ]
